import { Destination, TourPackage, Testimonial } from '@/lib/types'

export const destinations: Destination[] = [
  {
    id: 'maasai-mara',
    name: 'Maasai Mara',
    region: 'Southwest Kenya',
    highlights: ['Great Migration crossings', 'Big Five game drives', 'Maasai cultural visits'],
    bestMonths: ['July', 'August', 'September', 'October'],
    heroImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=1600&auto=format&fit=crop',
    summary: 'Kenya\'s flagship reserve with dramatic plains, predators, and world-class guiding.',
    wildlifeIndex: 98,
  },
  {
    id: 'amboseli',
    name: 'Amboseli',
    region: 'Southern Kenya',
    highlights: ['Elephant super-herds', 'Kilimanjaro views', 'Swamp birdlife'],
    bestMonths: ['June', 'July', 'January', 'February'],
    heroImage: 'https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=1600&auto=format&fit=crop',
    summary: 'Open wetlands and acacia scrub framed by Africa\'s highest mountain.',
    wildlifeIndex: 90,
  },
  {
    id: 'samburu',
    name: 'Samburu',
    region: 'Northern Kenya',
    highlights: ['Special five species', 'Riverine leopard sightings', 'Remote luxury camps'],
    bestMonths: ['June', 'July', 'August', 'January'],
    heroImage: 'https://images.unsplash.com/photo-1549366021-9f761d450615?q=80&w=1600&auto=format&fit=crop',
    summary: 'A rugged semi-arid ecosystem known for rare species and low tourist density.',
    wildlifeIndex: 86,
  },
  {
    id: 'laikipia',
    name: 'Laikipia Conservancies',
    region: 'Central Kenya',
    highlights: ['Conservation-first tourism', 'Night drives', 'Rhino tracking'],
    bestMonths: ['June', 'July', 'August', 'September'],
    heroImage: 'https://images.unsplash.com/photo-1627621312072-75d8f3f0fb6f?q=80&w=1600&auto=format&fit=crop',
    summary: 'Private conservancies with high-end lodges and exceptional conservation outcomes.',
    wildlifeIndex: 92,
  },
]

export const tourPackages: TourPackage[] = [
  {
    id: 'mara-premier-5d',
    title: 'Mara Premier Expedition',
    destinationId: 'maasai-mara',
    style: 'luxury',
    durationDays: 5,
    basePriceUsd: 2650,
    maxGuests: 6,
    includes: ['Luxury tented camp', 'Daily game drives', 'Airstrip transfers', 'Park fees'],
    featured: true,
  },
  {
    id: 'amboseli-family-4d',
    title: 'Amboseli Family Escape',
    destinationId: 'amboseli',
    style: 'family',
    durationDays: 4,
    basePriceUsd: 1890,
    maxGuests: 8,
    includes: ['Family suite lodging', 'Private guide', 'Kid-friendly itinerary', 'Meals'],
    featured: true,
  },
  {
    id: 'samburu-photo-6d',
    title: 'Samburu Photo Circuit',
    destinationId: 'samburu',
    style: 'photography',
    durationDays: 6,
    basePriceUsd: 2940,
    maxGuests: 5,
    includes: ['Photo vehicle setup', 'Golden-hour drives', 'Editing lounge', 'Conservancy fees'],
    featured: false,
  },
  {
    id: 'laikipia-adventure-7d',
    title: 'Laikipia Adventure Week',
    destinationId: 'laikipia',
    style: 'adventure',
    durationDays: 7,
    basePriceUsd: 3220,
    maxGuests: 6,
    includes: ['Bush walks', 'Night drives', 'Rhino tracking', 'All transfers'],
    featured: true,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    traveler: 'Elena Martin',
    country: 'Spain',
    rating: 5,
    quote: 'The planning quality was exceptional. Every transfer, camp handoff, and game drive worked with zero friction.',
  },
  {
    id: 't2',
    traveler: 'Andrew Collins',
    country: 'USA',
    rating: 5,
    quote: 'Our guide adapted quickly to weather and still delivered incredible sightings. Operationally very strong team.',
  },
  {
    id: 't3',
    traveler: 'Naomi Tanaka',
    country: 'Japan',
    rating: 5,
    quote: 'The custom pace for our family was perfect. The backend communication and booking updates were clear and fast.',
  },
]
